version: '3.8'

services:

  app:
    build: .
    restart: on-failure
    stop_signal: SIGINT
    depends_on:
      redis:
        condition: service_healthy
    env_file:
      - .env  # create this file first! :)
    healthcheck:
      test: python3 check_health.py || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
